"""empty message

Revision ID: e09f298de2e1
Revises: 
Create Date: 2025-01-18 22:02:36.657074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09f298de2e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pest_prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('pest_type', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pest_prediction')
    # ### end Alembic commands ###
def upgrade():
    op.add_column('user', sa.Column('profile_pic', sa.String(length=255), nullable=True, default='default.jpg'))

def downgrade():
    op.drop_column('user', 'profile_pic')
